/*
 * ConfigFrame.java
 *
 * Created on February 24, 2008, 4:35 PM
 */

package offstage.config;

import citibob.app.App;
import citibob.sql.SqlRun;

/**
 
 @author  citibob
 */
public class ConfigFrame extends javax.swing.JFrame
{
	
	/** Creates new form ConfigFrame */
	public ConfigFrame()
	{
		initComponents();
	}
	public void initRuntime(SqlRun str, App app)
	{
		resources.initRuntime(str, app);
	}
	/** This method is called from within the constructor to
	 initialize the form.
	 WARNING: Do NOT modify this code. The content of this method is
	 always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        resources = new offstage.config.ResourcePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(resources, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private offstage.config.ResourcePanel resources;
    // End of variables declaration//GEN-END:variables
	
}
