/*
 * EditConfigPanel.java
 *
 * Created on April 19, 2008, 9:18 PM
 */

package offstage.config;

/**
 *
 * @author  citibob
 */
public class EditConfigPanel extends javax.swing.JPanel {
	
	/** Creates new form EditConfigPanel */
	public EditConfigPanel() {
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        allText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        macText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        windowsText = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        linuxText = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        allText.setColumns(20);
        allText.setRows(5);
        jScrollPane1.setViewportView(allText);

        jTabbedPane1.addTab("All", jScrollPane1);

        macText.setColumns(20);
        macText.setRows(5);
        jScrollPane2.setViewportView(macText);

        jTabbedPane1.addTab("Mac", jScrollPane2);

        windowsText.setColumns(20);
        windowsText.setRows(5);
        jScrollPane3.setViewportView(windowsText);

        jTabbedPane1.addTab("Windows", jScrollPane3);

        linuxText.setColumns(20);
        linuxText.setRows(5);
        jScrollPane4.setViewportView(linuxText);

        jTabbedPane1.addTab("Linux", jScrollPane4);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);

        jButton2.setText("jButton2");
        jPanel1.add(jButton2);

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea allText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea linuxText;
    private javax.swing.JTextArea macText;
    private javax.swing.JTextArea windowsText;
    // End of variables declaration//GEN-END:variables
	
}
