/*
 * ResourcePanel.java
 *
 * Created on February 24, 2008, 10:27 AM
 */

package offstage.config;

import citibob.resource.ResModels;
import citibob.app.App;
import citibob.resource.ResKey;
import citibob.resource.ResSet;
import citibob.resource.Resource;
import citibob.resource.UpgradePlan;
import citibob.sql.SqlRunner;
import citibob.swing.table.JTypeTableModel;
import java.lang.Integer;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 
 @author  citibob
 */
public class ResourcePanel extends javax.swing.JPanel
{

App app;
	
Resource curResource;
ResKey curResKey;
Integer curVersion;
UpgradePlan curUPlan;

ResModels rmods;

	/** Creates new form ResourcePanel */
	public ResourcePanel()
	{
		initComponents();
	}
	
	public void initRuntime(SqlRunner str, App xapp)
	{
		this.app = xapp;
		ResSet rset = app.getResSet();
		rmods = new ResModels(str, app, app.getSysVersion());

		// Set up tables
		tResources.setModelU(rmods.resMod,
			new String[] {"Resource", "Required Version"},
			new String[] {"name", "reqversion"},
			null, app.getSwingerMap());
		
		this.tUversionIDs.setModelU(rmods.rkMod,
			new String[] {"Name"},
			new String[] {"name"},
			null, app.getSwingerMap());
		
		tAvailVersions.setModelU(rmods.availMod,
			new String[] {"Version", "Last Modified"},
			new String[] {"version", "lastmodified"},
			null, app.getSwingerMap());
		tAvailVersions.setRenderEditU("lastmodified", "MM/dd/yyyy");

		this.tUpgradePlans.setModelU(rmods.uplanMod,
			new String[] {"Source", "Plan"},
			new String[] {"uversionName0", "UpgradePlan"},
			null, app.getSwingerMap());
		tUpgradePlans.setRenderEditU("UpgradePlan", new ResModels.PathSFormat());
		
		
		// Select a Resource
		tResources.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
		public void valueChanged(ListSelectionEvent e) {
			int irow = e.getFirstIndex();
			if (irow < 0) return;
			setCurResource((Resource)rmods.resMod.getValueAt(e.getFirstIndex(), "Resource"));
		}});
		
		// Select a UVersionID
		tUversionIDs.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
		public void valueChanged(ListSelectionEvent e) {
			int irow = e.getFirstIndex();
			if (irow < 0) return;
			setCurResKey((ResKey)rmods.rkMod.getValueAt(e.getFirstIndex(), "ResKey"));
		}});

		// Select a version
		tAvailVersions.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
		public void valueChanged(ListSelectionEvent e) {
			int irow = e.getFirstIndex();
			if (irow < 0) return;
			setCurVersion((Integer)rmods.availMod.getValueAt(irow, "version"));
		}});

		// Select an Upgrade Plan
		tUpgradePlans.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
		public void valueChanged(ListSelectionEvent e) {
			int irow = e.getFirstIndex();
			if (irow < 0) return;
			// setCurUpgradePlan((UpgradePlan)rmods.availMod.getValueAt(irow, "UpgradePlan"));
		}});
	};
	
	
	void setCurResource(Resource r)
	{
		curResource = r;
		if (r == null) rmods.rkMod.clear();
		else rmods.rkMod.setData(r);
		setCurResKey(null);
	}

	void setCurResKey(ResKey rk)
	{
		curResKey = rk;
		if (rk == null) rmods.availMod.clear();
		else rmods.availMod.setData(rk.availVersions);
		setCurVersion(null);
	}
	
	void setCurVersion(Integer version)
	{
		curVersion = version;
		if (version == null) rmods.uplanMod.clear();
		else {
			ArrayList<UpgradePlan> plans = new ArrayList();

			// Get creator paths
			UpgradePlan uplan = curResKey.getCreatorPlan(version);
			if (uplan != null) plans.add(uplan);

			// Get upgrade paths
			for (int ver0 : curResKey.availVersions) {
				if (ver0 == version) continue;	// Skip trivial nop plans
				uplan = curResKey.getUpgradePlan(ver0, version);
				if (uplan != null) plans.add(uplan);
			}

			// Get paths to copy from another UVersionID of same vesrion
		
			// Display...
			rmods.uplanMod.setData(plans);
		}
		setCurUPlan(null);
	}
	
	void setCurUPlan(UpgradePlan uplan)
	{
		this.curUPlan = uplan;
	}
	/** This method is called from within the constructor to
	 initialize the form.
	 WARNING: Do NOT modify this code. The content of this method is
	 always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tResources = new citibob.swing.JTypeColTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tUversionIDs = new citibob.swing.JTypeColTable();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAvailVersions = new citibob.swing.JTypeColTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tUpgradePlans = new citibob.swing.JTypeColTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel3.setText("Resources");
        jPanel4.add(jLabel3, java.awt.BorderLayout.NORTH);

        tResources.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tResources.setHighlightMouseover(true);
        jScrollPane3.setViewportView(tResources);

        jPanel4.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jSplitPane2.setTopComponent(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel4.setText("Terms/Seasons");
        jPanel5.add(jLabel4, java.awt.BorderLayout.NORTH);

        tUversionIDs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tUversionIDs.setHighlightMouseover(true);
        jScrollPane4.setViewportView(tUversionIDs);

        jPanel5.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jSplitPane2.setBottomComponent(jPanel5);

        jSplitPane1.setLeftComponent(jSplitPane2);

        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel1.setText("Available Versions");
        jPanel2.add(jLabel1, java.awt.BorderLayout.NORTH);

        tAvailVersions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tAvailVersions.setHighlightMouseover(true);
        jScrollPane1.setViewportView(tAvailVersions);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane3.setTopComponent(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel2.setText("Upgrade Plans");
        jPanel3.add(jLabel2, java.awt.BorderLayout.NORTH);

        tUpgradePlans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tUpgradePlans.setHighlightMouseover(true);
        jScrollPane2.setViewportView(tUpgradePlans);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jSplitPane3.setBottomComponent(jPanel3);

        jSplitPane1.setRightComponent(jSplitPane3);

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private citibob.swing.JTypeColTable tAvailVersions;
    private citibob.swing.JTypeColTable tResources;
    private citibob.swing.JTypeColTable tUpgradePlans;
    private citibob.swing.JTypeColTable tUversionIDs;
    // End of variables declaration//GEN-END:variables
	
}
