/*
 * AccountFrame.java
 *
 * Created on February 15, 2008, 11:47 PM
 */

package offstage.accounts.gui;

import offstage.FrontApp;

/**
 
 @author  citibob
 */
public class AccountFrame extends javax.swing.JFrame
{
	
	/** Creates new form AccountFrame */
	public AccountFrame()
	{
		initComponents();
	}
	public void initRuntime(FrontApp fapp)
	{
		this.accountPanel1.initRuntime(fapp);
	}
	/** This method is called from within the constructor to
	 initialize the form.
	 WARNING: Do NOT modify this code. The content of this method is
	 always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        accountPanel1 = new offstage.accounts.gui.AccountPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accounting");

        jTabbedPane1.addTab("Account Editor", accountPanel1);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Window");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	/**
	 @param args the command line arguments
	 */
	public static void main(String args[])
	{
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new AccountFrame().setVisible(true);
			}
		});
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private offstage.accounts.gui.AccountPanel accountPanel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
	
}
