/*
 * AccountsPanel.java
 *
 * Created on December 10, 2007, 1:01 AM
 */

package offstage.accounts.gui;

import citibob.jschema.SchemaBuf;
import citibob.sql.SqlRunner;
import citibob.task.ActionTaskBinder;
import offstage.FrontApp;
import offstage.schema.ActransSchema;

/**
 *
 * @author  citibob
 */
public class AccountPanel extends javax.swing.JPanel
{
	
/** Creates new form AccountsPanel */
public AccountPanel()
{
	initComponents();
}
public void initRuntime(FrontApp fapp)
{

	// Bind our account actions
	ActionTaskBinder tbinder = new ActionTaskBinder(this, fapp.getGuiRunner(),
		transRegister.getTaskMap());
	tbinder.bind(this.bCash, "cash");
	tbinder.bind(this.bCheck, "check");
	tbinder.bind(this.bCc, "cc");
	tbinder.bind(this.bOtherTrans, "other");

	SchemaBuf actransSb = new SchemaBuf(fapp.getSchema("actrans"));
	transRegister.initRuntime(fapp, actransSb, 1);
}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        AccountPane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jKeyedComboBox1 = new citibob.swing.typed.JKeyedComboBox();
        jLabel4 = new javax.swing.JLabel();
        firstName = new citibob.swing.typed.JTypedLabel();
        lastName = new citibob.swing.typed.JTypedLabel();
        transRegister = new offstage.accounts.gui.TransRegPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        bCash = new javax.swing.JButton();
        bCheck = new javax.swing.JButton();
        bCc = new javax.swing.JButton();
        bOtherTrans = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        simpleSearchPanel1 = new offstage.gui.SimpleSearchPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTypeColTable1 = new citibob.swing.JTypeColTable();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        AccountPane.setPreferredSize(new java.awt.Dimension(484, 100));
        AccountPane.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Account: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel2, gridBagConstraints);

        jKeyedComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jKeyedComboBox1, gridBagConstraints);

        jLabel4.setText("Name: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel4, gridBagConstraints);

        firstName.setText("jTypedLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(firstName, gridBagConstraints);

        lastName.setText("jTypedLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(lastName, gridBagConstraints);

        AccountPane.add(jPanel1, java.awt.BorderLayout.PAGE_START);
        AccountPane.add(transRegister, java.awt.BorderLayout.CENTER);

        jPanel13.setPreferredSize(new java.awt.Dimension(484, 35));
        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel17.setText("Transaction:");
        jPanel13.add(jLabel17);

        bCash.setText("Cash");
        bCash.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel13.add(bCash);

        bCheck.setText("Check");
        bCheck.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel13.add(bCheck);

        bCc.setText("Credit");
        bCc.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel13.add(bCc);

        bOtherTrans.setText("Other");
        bOtherTrans.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel13.add(bOtherTrans);

        jLabel1.setText("     ");
        jPanel13.add(jLabel1);

        bDelete.setText("Delete");
        bDelete.setMargin(new java.awt.Insets(2, 2, 2, 2));
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        jPanel13.add(bDelete);

        AccountPane.add(jPanel13, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setLeftComponent(AccountPane);

        jPanel2.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(simpleSearchPanel1, gridBagConstraints);

        jTypeColTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTypeColTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(jScrollPane1, gridBagConstraints);

        jLabel3.setText("Balance Summary:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jLabel3, gridBagConstraints);

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

	private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_bDeleteActionPerformed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountPane;
    private javax.swing.JButton bCash;
    private javax.swing.JButton bCc;
    private javax.swing.JButton bCheck;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bOtherTrans;
    private citibob.swing.typed.JTypedLabel firstName;
    private citibob.swing.typed.JKeyedComboBox jKeyedComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private citibob.swing.JTypeColTable jTypeColTable1;
    private citibob.swing.typed.JTypedLabel lastName;
    private offstage.gui.SimpleSearchPanel simpleSearchPanel1;
    private offstage.accounts.gui.TransRegPanel transRegister;
    // End of variables declaration//GEN-END:variables
	
}
