/*
 * CheckSchoolPanel.java
 *
 * Created on June 5, 2008, 6:22 PM
 */

package offstage.swing.typed;

import citibob.swing.typed.*;
import citibob.app.App;
import citibob.swing.table.TableRowCounter;
import citibob.swing.typed.JTypedPanel;

/**
 *
 * @author  citibob
 */
public class IdSqlPanel extends JTypedPanel {
	
	/** Creates new form CheckSchoolPanel */
	public IdSqlPanel() {
		initComponents();
		
		super.setSubWidget(idSqlTable);
		
	}
	public IdSqlTable getTable() { return idSqlTable; }

	
	public void initRuntime(App app)
	{
		idSqlTable.initRuntime(app);
		
//			noEmail.setHighlightMouseover(false);
//		noEmail.executeQuery(str,
//			" select id from _mm" +
//			" where _mm.iscurrent and not _mm.hasemail;\n"
//			, "lastname,firstname");
	}

	public TableRowCounter newRowCounter()
	{
		final TableRowCounter counter = new TableRowCounter();
			counter.setModel(idSqlTable.getModelU());
		return counter;
	}

	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        idSqlTable = new offstage.swing.typed.IdSqlTable();

        setLayout(new java.awt.BorderLayout());

        idSqlTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(idSqlTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private offstage.swing.typed.IdSqlTable idSqlTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
	
}
