/*
 * RelEditorDialog.java
 *
 * Created on March 25, 2009, 9:30 PM
 */

package offstage.gui;

import citibob.app.App;

/**
 *
 * @author  citibob
 */
public class RelEditDialog extends javax.swing.JDialog {

App app;
	
public static final int ACTION_CANCEL = 0;
public static final int ACTION_OK = 1;
public static final int ACTION_DELETE = 2;

protected int action = ACTION_CANCEL;	// How this dialog was exited

	/** Creates new form RelEditorDialog */
	public RelEditDialog(java.awt.Frame parent) {
		super(parent, true);
		initComponents();
	}
	
	public void initRuntime(App app)
	{
		entityid0.initRuntime(app);
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        entityid0 = new offstage.swing.typed.EntityIDDropdown();
        entityid1 = new offstage.swing.typed.EntityIDDropdown();
        lRel = new citibob.swing.typed.JTypedLabel();
        jPanel2 = new javax.swing.JPanel();
        bOK = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        entityid0.setColName("entityid0"); // NOI18N
        entityid0.setPreferredSize(new java.awt.Dimension(200, 19));

        entityid1.setColName("entityid0"); // NOI18N
        entityid1.setPreferredSize(new java.awt.Dimension(200, 19));

        lRel.setText("jTypedLabel1");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(entityid1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(lRel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                    .add(entityid0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(entityid0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lRel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(11, 11, 11)
                .add(entityid1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        bOK.setText("OK");
        bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKActionPerformed(evt);
            }
        });
        jPanel2.add(bOK);

        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(bDelete);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
		// TODO add your handling code here:
		action = ACTION_DELETE;
		setVisible(false);
}//GEN-LAST:event_bDeleteActionPerformed

	private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
		action = ACTION_OK;
		setVisible(false);
		// TODO add your handling code here:
	}//GEN-LAST:event_bOKActionPerformed

	private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		action = ACTION_CANCEL;
		// TODO add your handling code here:
	}//GEN-LAST:event_formWindowClosing
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bOK;
    protected offstage.swing.typed.EntityIDDropdown entityid0;
    protected offstage.swing.typed.EntityIDDropdown entityid1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    protected citibob.swing.typed.JTypedLabel lRel;
    // End of variables declaration//GEN-END:variables
	
}
