/*
 * FrontDeskFrame.java
 *
 * Created on April 13, 2008, 4:46 PM
 */

package offstage.frontdesk;

import citibob.sql.SqlRun;
import offstage.FrontApp;

/**
 
 @author  citibob
 */
public class FrontDeskFrame extends javax.swing.JFrame
{
	
	/** Creates new form FrontDeskFrame */
	public FrontDeskFrame()
	{
		initComponents();
	}
	
	public void initRuntime(SqlRun str, FrontApp app)
	{
		this.openClassPanel1.initRuntime(str, app);
	}
	
	/** This method is called from within the constructor to
	 initialize the form.
	 WARNING: Do NOT modify this code. The content of this method is
	 always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        openClassPanel1 = new offstage.frontdesk.OpenClassPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.addTab("Open Class Registration", openClassPanel1);

        jPanel1.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Window");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	/**
	 @param args the command line arguments
	 */
	public static void main(String args[])
	{
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new FrontDeskFrame().setVisible(true);
			}
		});
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private offstage.frontdesk.OpenClassPanel openClassPanel1;
    // End of variables declaration//GEN-END:variables
	
}
